development:
  adapter: postgresql
  encoding: unicode
  database: six_degrees_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: six_degrees_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: six_degrees_production
  pool: 5
